import React, { useEffect, useState, useCallback } from "react";
import { View, Text, Alert, Platform, ScrollView, RefreshControl } from "react-native";
import * as WebBrowser from "expo-web-browser";
import * as Linking from "expo-linking";
import { Screen, Card, PrimaryButton, GhostButton, Pill } from "../../components/ui";
import { supabase } from "../../api/supabase";
import { API_BASE_URL } from "../../config/api";
import { useTheme } from "../../context/ThemeContext";

export default function TopUpCheckoutScreen({ navigation, route }) {
    const { ref, url } = route.params;

    const [status, setStatus] = useState("PENDING");
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);

    const pollOnce = useCallback(async () => {
        try {
            setRefreshing(true);
            const { data: s } = await supabase.auth.getSession();
            const token = s?.session?.access_token;
            if (!token) return;

            const res = await fetch(`${API_BASE_URL}/wallet/topup/${ref}`, {
                headers: { Authorization: `Bearer ${token}` },
            });
            const json = await res.json();
            if (res.ok && json?.status) {
                setStatus(json.status);
            }
        } catch (e) {
            // silent polling errors
        } finally {
            setRefreshing(false);
        }
    }, [ref]);

    useEffect(() => {
        let channel;

        (async () => {
            // 0. Generate Callback URL (e.g. exp://... or era-wallet://...)
            const callbackUrl = Linking.createURL("/");
            console.log("🔗 Callback URL:", callbackUrl);

            // 1. Get Checkout Session (Passing the callback URL)
            // Note: We already have 'url' from navigation params, but it might not have the correct redirect
            // If the backend already generated the URL, we might need to recreate it or just use it.
            // Actually, the backend should use the callbackUrl we provide.
            
            // WAIT - the 'url' passed in route.params was generated by startTopup in TopUpScreen.
            // I should modify TopUpScreen.jsx to pass the callbackUrl.
            
            setLoading(false);

            // 1. Open Browser (Using AuthSession for auto-dismiss capability)
            const result = await WebBrowser.openAuthSessionAsync(url, callbackUrl);

            // 2. Poll immediately to check status after browser closes/returns
            await pollOnce();

            // Navigate dynamically based on redirect actions (e.g. Cancel / Success action buttons)
            if (result.type === "success" && result.url) {
                if (result.url.includes("action=home")) {
                    navigation.reset({
                        index: 0,
                        routes: [{ name: "Home", params: { refresh: Date.now() } }],
                    });
                    return;
                } else if (result.url.includes("action=change_method")) {
                    navigation.goBack();
                    return;
                }
            } else if (result.type === "cancel" || result.type === "dismiss") {
                // If they closed the browser manually or via the Done button
                // we should check the current status one last time to be sure
                const { data: s } = await supabase.auth.getSession();
                const token = s?.session?.access_token;
                if (token) {
                    const res = await fetch(`${API_BASE_URL}/wallet/topup/${ref}`, {
                        headers: { Authorization: `Bearer ${token}` },
                    });
                    const json = await res.json();
                    if (res.ok && json?.status === "PAID") {
                        // Skip the alert and just go home since they just closed a success page
                        navigation.reset({
                            index: 0,
                            routes: [{ name: "Home", params: { refresh: Date.now() } }],
                        });
                        return;
                    }
                }
            }

            // 3. ✨ REALTIME SUBSCRIPTION (Senior Dev Approach)
            // Listen for UPDATES on this specific topup ID
            channel = supabase
                .channel(`topup-${ref}`)
                .on(
                    "postgres_changes",
                    {
                        event: "UPDATE",
                        schema: "public",
                        table: "wallet_topups",
                        filter: `id=eq.${ref}`,
                    },
                    (payload) => {
                        console.log("🔥 Realtime Update:", payload);
                        if (payload.new?.status) {
                            setStatus(payload.new.status);
                        }
                    }
                )
                .subscribe();
        })();

        return () => {
            if (channel) supabase.removeChannel(channel);
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
        if (status === "PAID") {
            navigation.reset({
                index: 0,
                routes: [{ name: "Home", params: { refresh: Date.now() } }],
            });
        }
    }, [status, navigation]);

    const { theme, isDarkMode } = useTheme();

    return (
        <Screen
            title="Processing Payment"
            subtitle="Follow instructions in the checkout page to complete your top up."
            onBack={() => navigation.goBack()}
            theme={theme}
        >
            <ScrollView
                style={{ flex: 1 }}
                contentContainerStyle={{ paddingBottom: 100 }}
                showsVerticalScrollIndicator={false}
                refreshControl={
                    <RefreshControl
                        refreshing={refreshing}
                        onRefresh={pollOnce}
                        tintColor={theme.accent}
                        colors={[theme.accent]}
                    />
                }
            >
                <Card theme={theme} style={{ marginTop: 20, padding: 20 }}>
                    <Pill text="PayMongo Checkout" theme={theme} />

                    <View style={{ marginTop: 30 }}>
                        <Text style={{
                            color: theme.textSecondary,
                            fontSize: 12,
                            fontWeight: "800",
                            textTransform: "uppercase",
                            letterSpacing: 1.5
                        }}>
                            Reference ID
                        </Text>
                        <Text style={{
                            marginTop: 10,
                            color: theme.text,
                            fontWeight: "900",
                            fontSize: 18,
                            letterSpacing: 0.5,
                            fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace'
                        }}>
                            {ref}
                        </Text>
                    </View>

                    <View
                        style={{
                            marginTop: 30,
                            borderRadius: 24,
                            padding: 24,
                            borderWidth: 1,
                            borderColor: theme.border,
                            backgroundColor: isDarkMode ? "rgba(255,107,0,0.03)" : "rgba(255,107,0,0.02)",
                            shadowColor: "#000",
                            shadowOffset: { width: 0, height: 4 },
                            shadowOpacity: 0.05,
                            shadowRadius: 10,
                            elevation: 2
                        }}
                    >
                        <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                            <Text style={{ color: theme.textSecondary, fontWeight: "700", fontSize: 14 }}>Status</Text>
                            <View style={{
                                backgroundColor: status === "PAID" ? theme.successBg : status === "PENDING" ? theme.warningBg : theme.dangerBg,
                                paddingHorizontal: 12,
                                paddingVertical: 6,
                                borderRadius: 10,
                                borderWidth: 1,
                                borderColor: status === "PAID" ? theme.success : status === "PENDING" ? theme.warning : theme.danger
                            }}>
                                <Text style={{
                                    color: status === "PAID" ? theme.success : status === "PENDING" ? (isDarkMode ? theme.warning : "#827100") : theme.danger,
                                    fontWeight: "900",
                                    fontSize: 11,
                                    letterSpacing: 0.5
                                }}>
                                    {status === "PAID" ? "SUCCESS" : status === "PENDING" ? "PENDING" : status}
                                </Text>
                            </View>
                        </View>

                        <Text style={{ color: theme.text, fontWeight: "900", fontSize: 28, letterSpacing: -0.5 }}>
                            {loading ? "Initializing..." : status === "PENDING" ? "Awaiting Payment" : (status === "PROCESSING" ? "Processing..." : status)}
                        </Text>

                        <Text style={{ marginTop: 16, color: theme.textSecondary, fontSize: 13, lineHeight: 20, fontWeight: "500" }}>
                            Your wallet will be credited automatically once the payment is confirmed. Please do not close the app during the process.
                        </Text>
                    </View>
                </Card>

                <View style={{ marginTop: 40 }}>
                    <Text style={{
                        textAlign: 'center',
                        color: theme.textMuted,
                        fontSize: 13,
                        fontWeight: "600",
                        lineHeight: 18
                    }}>
                        Swipe down to check for updates manually if the status hasn't changed.
                    </Text>
                </View>
            </ScrollView>
        </Screen>
    );
}
